In [105]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [106]:
df=pd.read_csv(r'C:\Users\Dell\Documents\project excel\carprices.csv')

In [107]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Car Model      13 non-null     object
 1   Mileage        13 non-null     int64 
 2   Sell Price($)  13 non-null     int64 
 3   Age(yrs)       13 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 548.0+ bytes


In [109]:
dummy=pd.get_dummies(df['Car Model'])
dummy

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [110]:
df_dummy=pd.concat([df,dummy],axis=1)
df_dummy

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [111]:
df_dummy.drop(['Car Model','BMW X5'],axis=1,inplace=True)
df_dummy

Mileage  Sell Price($)  Age(yrs)  Audi A5  Mercedez Benz C class
0     69000          18000         6        0                      0
1     35000          34000         3        0                      0
2     57000          26100         5        0                      0
3     22500          40000         2        0                      0
4     46000          31500         4        0                      0
5     59000          29400         5        1                      0
6     52000          32000         5        1                      0
7     72000          19300         6        1                      0
8     91000          12000         8        1                      0
9     67000          22000         6        0                      1
10    83000          20000         7        0                      1
11    79000          21000         7        0                      1
12    59000          33000         5        0                      1

In [112]:
x=df_dummy.drop(['Sell Price($)'],axis=1)
x

Mileage  Age(yrs)  Audi A5  Mercedez Benz C class
0     69000         6        0                      0
1     35000         3        0                      0
2     57000         5        0                      0
3     22500         2        0                      0
4     46000         4        0                      0
5     59000         5        1                      0
6     52000         5        1                      0
7     72000         6        1                      0
8     91000         8        1                      0
9     67000         6        0                      1
10    83000         7        0                      1
11    79000         7        0                      1
12    59000         5        0                      1

In [113]:
y=df_dummy['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [114]:
model=linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [115]:
# Predict price of a mercedez benz that is 4 yr old with mileage 45000
 #Predict price of a BMW X5 that is 7 yr old with mileage 86000
# Tell me the score (accuracy) of your model. (Hint: use LinearRegression().score())


In [116]:
model.predict([[45000,4,0,1]])

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721031])

In [117]:
model.predict([[86000,7,0,0]])

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313267])

In [76]:
model.score(x,y)

0.9417050937281082

In [78]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [79]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [80]:
df_le=df
df_le['Car Model']=le.fit_transform(df_le['Car Model'])
df_le

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [81]:
y=df_le[['Car Model','Mileage']].values
y

array([[    1, 69000],
       [    1, 35000],
       [    1, 57000],
       [    1, 22500],
       [    1, 46000],
       [    0, 59000],
       [    0, 52000],
       [    0, 72000],
       [    0, 91000],
       [    2, 67000],
       [    2, 83000],
       [    2, 79000],
       [    2, 59000]], dtype=int64)

In [82]:
x=df_le[['Sell Price($)']].values
x

array([[18000],
       [34000],
       [26100],
       [40000],
       [31500],
       [29400],
       [32000],
       [19300],
       [12000],
       [22000],
       [20000],
       [21000],
       [33000]], dtype=int64)

In [83]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')

In [84]:
X = ct.fit_transform(y)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04]])

In [85]:
X = X[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04],
       [1.00e+00, 0.00e+00, 3.50e+04],
       [1.00e+00, 0.00e+00, 5.70e+04],
       [1.00e+00, 0.00e+00, 2.25e+04],
       [1.00e+00, 0.00e+00, 4.60e+04],
       [0.00e+00, 0.00e+00, 5.90e+04],
       [0.00e+00, 0.00e+00, 5.20e+04],
       [0.00e+00, 0.00e+00, 7.20e+04],
       [0.00e+00, 0.00e+00, 9.10e+04],
       [0.00e+00, 1.00e+00, 6.70e+04],
       [0.00e+00, 1.00e+00, 8.30e+04],
       [0.00e+00, 1.00e+00, 7.90e+04],
       [0.00e+00, 1.00e+00, 5.90e+04]])

In [86]:
model.fit(X,x)

LinearRegression()

In [87]:
# Predict price of a mercedez benz that is 4 yr old with mileage 45000
 #Predict price of a BMW X5 that is 7 yr old with mileage 86000
# Tell me the score (accuracy) of your model. (Hint: use LinearRegression().score())


In [103]:
model.predict([[0,1,45000,4]])

ValueError: X has 4 features, but LinearRegression is expecting 3 features as input.

In [99]:
model.predict([[0,7,86000]])

array([[32328.95413131]])

In [98]:
model.score(X,x)

0.9407475372588112